-- unary minus
CREATE FUNCTION "uminus_float"(float4) RETURNS float4 AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "uminus_double"(float8) RETURNS float8 AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "uminus_integer"(decimal) RETURNS decimal AS 'MODULE_PATHNAME','uminus_decimal' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "uminus_decimal"(decimal) RETURNS decimal AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "uminus_rdfbox"(rdfbox) RETURNS rdfbox AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;

-- addition
CREATE FUNCTION "add_float"(float4,float4) RETURNS float4 AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "add_double"(float8,float8) RETURNS float8 AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "add_integer"(decimal,decimal) RETURNS decimal AS 'MODULE_PATHNAME','add_decimal' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "add_decimal"(decimal,decimal) RETURNS decimal AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "add_rdfbox"(rdfbox,rdfbox) RETURNS rdfbox AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;

-- subtraction
CREATE FUNCTION "sub_float"(float4,float4) RETURNS float4 AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "sub_double"(float8,float8) RETURNS float8 AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "sub_integer"(decimal,decimal) RETURNS decimal AS 'MODULE_PATHNAME','sub_decimal' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "sub_decimal"(decimal,decimal) RETURNS decimal AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "sub_rdfbox"(rdfbox,rdfbox) RETURNS rdfbox AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;

-- multiplication
CREATE FUNCTION "mul_float"(float4,float4) RETURNS float4 AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "mul_double"(float8,float8) RETURNS float8 AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "mul_integer"(decimal,decimal) RETURNS decimal AS 'MODULE_PATHNAME','mul_decimal' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "mul_decimal"(decimal,decimal) RETURNS decimal AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "mul_rdfbox"(rdfbox,rdfbox) RETURNS rdfbox AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;

-- division
CREATE FUNCTION "div_float"(float4,float4) RETURNS float4 AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "div_double"(float8,float8) RETURNS float8 AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "div_integer"(decimal,decimal) RETURNS decimal AS 'MODULE_PATHNAME','div_decimal' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "div_decimal"(decimal,decimal) RETURNS decimal AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
CREATE FUNCTION "div_rdfbox"(rdfbox,rdfbox) RETURNS rdfbox AS 'MODULE_PATHNAME' LANGUAGE C IMMUTABLE STRICT;
